<a href="https://colab.research.google.com/github/pedrosampaiom2007-gif/cp1-Andre/blob/main/Desafio_Final_Energia_ONS_API_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio Final — Análise de Dados de Energia com API Pública

**Curso:** Ciência da Computação  
**Disciplina:** Soluções em Energias Renováveis e Sustentáveis

## Situação-problema

Uma equipe de planejamento energético precisa analisar o comportamento da carga elétrica de uma região atendida pelo Sistema Interligado Nacional (SIN).

Os dados serão obtidos diretamente de uma API pública do **Operador Nacional do Sistema Elétrico (ONS)**. A conexão com a API e a preparação inicial do JSON já estão fornecidas. A partir daí, sua equipe deverá construir o DataFrame, organizar os dados, criar recortes, calcular indicadores, produzir gráficos e elaborar um relatório técnico.

> Todos os códigos, resultados, gráficos e respostas devem permanecer neste mesmo Notebook.

## 1. Fonte dos dados

API pública de **Carga Verificada do ONS**:

- Portal: https://dados.ons.org.br/
- Conjunto de dados: https://dados.ons.org.br/dataset/carga-energia-verificada

Neste notebook será utilizada inicialmente a área **SP — São Paulo**, no período de **01/08/2025 a 07/08/2025**.

## 2. Bibliotecas

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 3. Consulta à API

Esta célula está pronta. Não é necessário conhecer `requests` para realizar o desafio.

In [2]:
url = "https://apicarga.ons.org.br/prd/cargaverificada"

parametros = {
    "dat_inicio": "2025-08-01",
    "dat_fim": "2025-08-07",
    "cod_areacarga": "SP"
}

response = requests.get(url, params=parametros, timeout=30)

print("Status:", response.status_code)
print("URL:", response.url)

response.raise_for_status()
dados_json = response.json()

Status: 200
URL: https://apicarga.ons.org.br/prd/cargaverificada?dat_inicio=2025-08-01&dat_fim=2025-08-07&cod_areacarga=SP

## 4. Preparação inicial do JSON

A célula abaixo localiza a lista principal de registros retornada pela API e a armazena em `registros`.

In [3]:
if isinstance(dados_json, list):
    registros = dados_json

elif isinstance(dados_json, dict):
    chaves_com_lista = [
        chave for chave, valor in dados_json.items()
        if isinstance(valor, list)
    ]

    if not chaves_com_lista:
        raise ValueError("A resposta não contém uma lista de registros.")

    chave_registros = chaves_com_lista[0]
    registros = dados_json[chave_registros]
    print("Chave utilizada:", chave_registros)

else:
    raise TypeError("Formato de JSON não reconhecido.")

print("Tipo:", type(registros))
print("Quantidade de registros:", len(registros))

if registros:
    print("\nPrimeiro registro:")
    print(registros[0])

Tipo: <class 'list'>
Quantidade de registros: 336

Primeiro registro:
{'cod_areacarga': 'SP', 'din_atualizacao': '2026-08-14T05:58:29.574Z', 'dat_referencia': '2025-08-01', 'din_referenciautc': '2025-08-01T03:30:00.000Z', 'val_cargaglobal': 15913.618, 'val_cargaglobalcons': 15913.618, 'val_cargaglobalsmmgd': 15892.488, 'val_cargasupervisionada': 14421.112, 'val_carganaosupervisionada': 1471.3759, 'val_cargammgd': 21.13, 'val_consistencia': 0}

In [4]:
type(registros)

list

In [5]:
registros

[{'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T03:30:00.000Z',
  'val_cargaglobal': 15913.618,
  'val_cargaglobalcons': 15913.618,
  'val_cargaglobalsmmgd': 15892.488,
  'val_cargasupervisionada': 14421.112,
  'val_carganaosupervisionada': 1471.3759,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T04:00:00.000Z',
  'val_cargaglobal': 15251.414,
  'val_cargaglobalcons': 15251.414,
  'val_cargaglobalsmmgd': 15230.284,
  'val_cargasupervisionada': 13758.101,
  'val_carganaosupervisionada': 1472.184,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T04:30:00.000Z',
  'val_cargaglobal': 14606.733,
  'val_cargaglobalcons': 14606.733,
  'val_cargaglobalsmmgd': 14585.604,
  'val_cargasupervisionada': 13112.602,
  'val_carganaosupervisionada': 1473.0022,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T05:00:00.000Z',
  'val_cargaglobal': 14182.29,
  'val_cargaglobalcons': 14182.29,
  'val_cargaglobalsmmgd': 14161.16,
  'val_cargasupervisionada': 12687.433,
  'val_carganaosupervisionada': 1473.7275,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T05:30:00.000Z',
  'val_cargaglobal': 13838.488,
  'val_cargaglobalcons': 13838.488,
  'val_cargaglobalsmmgd': 13817.358,
  'val_cargasupervisionada': 12342.648,
  'val_carganaosupervisionada': 1474.7096,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T06:00:00.000Z',
  'val_cargaglobal': 13672.563,
  'val_cargaglobalcons': 13672.563,
  'val_cargaglobalsmmgd': 13651.434,
  'val_cargasupervisionada': 12174.674,
  'val_carganaosupervisionada': 1476.7596,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T06:30:00.000Z',
  'val_cargaglobal': 13548.542,
  'val_cargaglobalcons': 13548.542,
  'val_cargaglobalsmmgd': 13527.412,
  'val_cargasupervisionada': 12049.024,
  'val_carganaosupervisionada': 1478.3882,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T07:00:00.000Z',
  'val_cargaglobal': 13634.049,
  'val_cargaglobalcons': 13634.049,
  'val_cargaglobalsmmgd': 13612.919,
  'val_cargasupervisionada': 12134.907,
  'val_carganaosupervisionada': 1478.012,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T07:30:00.000Z',
  'val_cargaglobal': 13733.728,
  'val_cargaglobalcons': 13733.728,
  'val_cargaglobalsmmgd': 13712.598,
  'val_cargasupervisionada': 12235.872,
  'val_carganaosupervisionada': 1476.7253,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T08:00:00.000Z',
  'val_cargaglobal': 13958.203,
  'val_cargaglobalcons': 13958.203,
  'val_cargaglobalsmmgd': 13937.073,
  'val_cargasupervisionada': 12461.951,
  'val_carganaosupervisionada': 1475.122,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T08:30:00.000Z',
  'val_cargaglobal': 14637.415,
  'val_cargaglobalcons': 14637.415,
  'val_cargaglobalsmmgd': 14616.285,
  'val_cargasupervisionada': 13143.165,
  'val_carganaosupervisionada': 1473.12,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T09:00:00.000Z',
  'val_cargaglobal': 15389.913,
  'val_cargaglobalcons': 15389.913,
  'val_cargaglobalsmmgd': 15368.783,
  'val_cargasupervisionada': 13898.176,
  'val_carganaosupervisionada': 1470.6072,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T09:30:00.000Z',
  'val_cargaglobal': 16570.408,
  'val_cargaglobalcons': 16570.408,
  'val_cargaglobalsmmgd': 16549.277,
  'val_cargasupervisionada': 15081.01,
  'val_carganaosupervisionada': 1468.2671,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T10:00:00.000Z',
  'val_cargaglobal': 16844.27,
  'val_cargaglobalcons': 16844.27,
  'val_cargaglobalsmmgd': 16803.602,
  'val_cargasupervisionada': 15336.101,
  'val_carganaosupervisionada': 1467.502,
  'val_cargammgd': 40.6685,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T10:30:00.000Z',
  'val_cargaglobal': 17564.123,
  'val_cargaglobalcons': 17564.123,
  'val_cargaglobalsmmgd': 17240.445,
  'val_cargasupervisionada': 15774.4,
  'val_carganaosupervisionada': 1466.044,
  'val_cargammgd': 323.6768,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T11:00:00.000Z',
  'val_cargaglobal': 18096.023,
  'val_cargaglobalcons': 18096.023,
  'val_cargaglobalsmmgd': 17415.6,
  'val_cargasupervisionada': 15954.084,
  'val_carganaosupervisionada': 1461.5154,
  'val_cargammgd': 680.4232,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T11:30:00.000Z',
  'val_cargaglobal': 18629.395,
  'val_cargaglobalcons': 18629.395,
  'val_cargaglobalsmmgd': 17409.6,
  'val_cargasupervisionada': 15953.951,
  'val_carganaosupervisionada': 1455.6488,
  'val_cargammgd': 1219.7958,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T12:00:00.000Z',
  'val_cargaglobal': 18825.176,
  'val_cargaglobalcons': 18825.176,
  'val_cargaglobalsmmgd': 17097.592,
  'val_cargasupervisionada': 15648.688,
  'val_carganaosupervisionada': 1448.904,
  'val_cargammgd': 1727.5842,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T12:30:00.000Z',
  'val_cargaglobal': 19056.504,
  'val_cargaglobalcons': 19056.504,
  'val_cargaglobalsmmgd': 16850.477,
  'val_cargasupervisionada': 15407.757,
  'val_carganaosupervisionada': 1442.7206,
  'val_cargammgd': 2206.0276,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T13:00:00.000Z',
  'val_cargaglobal': 19427.822,
  'val_cargaglobalcons': 19427.822,
  'val_cargaglobalsmmgd': 16792.59,
  'val_cargasupervisionada': 15353.431,
  'val_carganaosupervisionada': 1439.1598,
  'val_cargammgd': 2635.2324,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T13:30:00.000Z',
  'val_cargaglobal': 19648.512,
  'val_cargaglobalcons': 19648.512,
  'val_cargaglobalsmmgd': 16638.367,
  'val_cargasupervisionada': 15201.553,
  'val_carganaosupervisionada': 1436.8154,
  'val_cargammgd': 3010.1455,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T14:00:00.000Z',
  'val_cargaglobal': 19987.754,
  'val_cargaglobalcons': 19987.754,
  'val_cargaglobalsmmgd': 16673.879,
  'val_cargasupervisionada': 15239.052,
  'val_carganaosupervisionada': 1434.8273,
  'val_cargammgd': 3313.8745,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T14:30:00.000Z',
  'val_cargaglobal': 20126.986,
  'val_cargaglobalcons': 20126.986,
  'val_cargaglobalsmmgd': 16588.04,
  'val_cargasupervisionada': 15154.42,
  'val_carganaosupervisionada': 1433.6187,
  'val_cargammgd': 3538.9473,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T15:00:00.000Z',
  'val_cargaglobal': 20126.97,
  'val_cargaglobalcons': 20126.97,
  'val_cargaglobalsmmgd': 16446.277,
  'val_cargasupervisionada': 15013.091,
  'val_carganaosupervisionada': 1433.1873,
  'val_cargammgd': 3680.6926,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T15:30:00.000Z',
  'val_cargaglobal': 19785.258,
  'val_cargaglobalcons': 19785.258,
  'val_cargaglobalsmmgd': 16049.248,
  'val_cargasupervisionada': 14616.108,
  'val_carganaosupervisionada': 1433.1396,
  'val_cargammgd': 3736.0098,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T16:00:00.000Z',
  'val_cargaglobal': 19630.8,
  'val_cargaglobalcons': 19630.8,
  'val_cargaglobalsmmgd': 15926.451,
  'val_cargasupervisionada': 14492.658,
  'val_carganaosupervisionada': 1433.7927,
  'val_cargammgd': 3704.3503,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T16:30:00.000Z',
  'val_cargaglobal': 19944.734,
  'val_cargaglobalcons': 19944.734,
  'val_cargaglobalsmmgd': 16358.286,
  'val_cargasupervisionada': 14924.406,
  'val_carganaosupervisionada': 1433.8798,
  'val_cargammgd': 3586.448,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T17:00:00.000Z',
  'val_cargaglobal': 20101.248,
  'val_cargaglobalcons': 20101.248,
  'val_cargaglobalsmmgd': 16715.695,
  'val_cargasupervisionada': 15284.566,
  'val_carganaosupervisionada': 1431.1292,
  'val_cargammgd': 3385.552,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T17:30:00.000Z',
  'val_cargaglobal': 20149.096,
  'val_cargaglobalcons': 20149.096,
  'val_cargaglobalsmmgd': 17042.973,
  'val_cargasupervisionada': 15614.157,
  'val_carganaosupervisionada': 1428.8147,
  'val_cargammgd': 3106.1228,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T18:00:00.000Z',
  'val_cargaglobal': 20149.994,
  'val_cargaglobalcons': 20149.994,
  'val_cargaglobalsmmgd': 17394.816,
  'val_cargasupervisionada': 15966.112,
  'val_carganaosupervisionada': 1428.7037,
  'val_cargammgd': 2755.177,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T18:30:00.000Z',
  'val_cargaglobal': 20156.96,
  'val_cargaglobalcons': 20156.96,
  'val_cargaglobalsmmgd': 17816.303,
  'val_cargasupervisionada': 16387.63,
  'val_carganaosupervisionada': 1428.6711,
  'val_cargammgd': 2340.6584,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T19:00:00.000Z',
  'val_cargaglobal': 20130.299,
  'val_cargaglobalcons': 20130.299,
  'val_cargaglobalsmmgd': 18249.098,
  'val_cargasupervisionada': 16821.352,
  'val_carganaosupervisionada': 1427.7465,
  'val_cargammgd': 1881.2015,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T19:30:00.000Z',
  'val_cargaglobal': 20111.898,
  'val_cargaglobalcons': 20111.898,
  'val_cargaglobalsmmgd': 18732.162,
  'val_cargasupervisionada': 17304.648,
  'val_carganaosupervisionada': 1427.5135,
  'val_cargammgd': 1379.7368,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T20:00:00.000Z',
  'val_cargaglobal': 20268.64,
  'val_cargaglobalcons': 20268.64,
  'val_cargaglobalsmmgd': 19388.738,
  'val_cargasupervisionada': 17958.64,
  'val_carganaosupervisionada': 1430.0977,
  'val_cargammgd': 879.9032,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T20:30:00.000Z',
  'val_cargaglobal': 20384.635,
  'val_cargaglobalcons': 20384.635,
  'val_cargaglobalsmmgd': 20019.814,
  'val_cargasupervisionada': 18585.818,
  'val_carganaosupervisionada': 1433.9957,
  'val_cargammgd': 364.8194,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T21:00:00.000Z',
  'val_cargaglobal': 21088.959,
  'val_cargaglobalcons': 21088.959,
  'val_cargaglobalsmmgd': 20955.12,
  'val_cargasupervisionada': 19516.37,
  'val_carganaosupervisionada': 1438.7495,
  'val_cargammgd': 133.8406,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T21:30:00.000Z',
  'val_cargaglobal': 22398.36,
  'val_cargaglobalcons': 22398.36,
  'val_cargaglobalsmmgd': 22377.096,
  'val_cargasupervisionada': 20933.746,
  'val_carganaosupervisionada': 1443.3496,
  'val_cargammgd': 21.2638,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T22:00:00.000Z',
  'val_cargaglobal': 23185.312,
  'val_cargaglobalcons': 23185.312,
  'val_cargaglobalsmmgd': 23164.182,
  'val_cargasupervisionada': 21717.934,
  'val_carganaosupervisionada': 1446.2487,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T22:30:00.000Z',
  'val_cargaglobal': 22903.314,
  'val_cargaglobalcons': 22903.314,
  'val_cargaglobalsmmgd': 22882.184,
  'val_cargasupervisionada': 21433.58,
  'val_carganaosupervisionada': 1448.6025,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T23:00:00.000Z',
  'val_cargaglobal': 22358.701,
  'val_cargaglobalcons': 22358.701,
  'val_cargaglobalsmmgd': 22337.57,
  'val_cargasupervisionada': 20886.078,
  'val_carganaosupervisionada': 1451.4915,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-01T23:30:00.000Z',
  'val_cargaglobal': 21697.979,
  'val_cargaglobalcons': 21697.979,
  'val_cargaglobalsmmgd': 21676.848,
  'val_cargasupervisionada': 20223.252,
  'val_carganaosupervisionada': 1453.5953,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T00:00:00.000Z',
  'val_cargaglobal': 21385.326,
  'val_cargaglobalcons': 21385.326,
  'val_cargaglobalsmmgd': 21364.195,
  'val_cargasupervisionada': 19911.168,
  'val_carganaosupervisionada': 1453.0271,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T00:30:00.000Z',
  'val_cargaglobal': 20919.314,
  'val_cargaglobalcons': 20919.314,
  'val_cargaglobalsmmgd': 20898.184,
  'val_cargasupervisionada': 19445.617,
  'val_carganaosupervisionada': 1452.5674,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T01:00:00.000Z',
  'val_cargaglobal': 20234.748,
  'val_cargaglobalcons': 20234.748,
  'val_cargaglobalsmmgd': 20213.617,
  'val_cargasupervisionada': 18758.58,
  'val_carganaosupervisionada': 1455.0361,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T01:30:00.000Z',
  'val_cargaglobal': 19448.836,
  'val_cargaglobalcons': 19448.836,
  'val_cargaglobalsmmgd': 19427.705,
  'val_cargasupervisionada': 17969.277,
  'val_carganaosupervisionada': 1458.4272,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T02:00:00.000Z',
  'val_cargaglobal': 18866.266,
  'val_cargaglobalcons': 18866.266,
  'val_cargaglobalsmmgd': 18845.135,
  'val_cargasupervisionada': 17385.73,
  'val_carganaosupervisionada': 1459.4052,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T02:30:00.000Z',
  'val_cargaglobal': 17996.322,
  'val_cargaglobalcons': 17996.322,
  'val_cargaglobalsmmgd': 17975.191,
  'val_cargasupervisionada': 16510.412,
  'val_carganaosupervisionada': 1464.7788,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:29.574Z',
  'dat_referencia': '2025-08-01',
  'din_referenciautc': '2025-08-02T03:00:00.000Z',
  'val_cargaglobal': 17207.49,
  'val_cargaglobalcons': 17207.49,
  'val_cargaglobalsmmgd': 17186.36,
  'val_cargasupervisionada': 15698.728,
  'val_carganaosupervisionada': 1487.6323,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:37.837Z',
  'dat_referencia': '2025-08-02',
  'din_referenciautc': '2025-08-02T03:30:00.000Z',
  'val_cargaglobal': 16420.523,
  'val_cargaglobalcons': 16420.523,
  'val_cargaglobalsmmgd': 16399.393,
  'val_cargasupervisionada': 14893.586,
  'val_carganaosupervisionada': 1505.806,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},
 {'cod_areacarga': 'SP',
  'din_atualizacao': '2026-08-14T05:58:37.837Z',
  'dat_referencia': '2025-08-02',
  'din_referenciautc': '2025-08-02T04:00:00.000Z',
  'val_cargaglobal': 15758.82,
  'val_cargaglobalcons': 15758.82,
  'val_cargaglobalsmmgd': 15737.69,
  'val_cargasupervisionada': 14230.481,
  'val_carganaosupervisionada': 1507.2089,
  'val_cargammgd': 21.13,
  'val_consistencia': 0},

## A partir daqui, o trabalho é da equipe

DESAFIO 1 — Construção e inspeção do DataFrame

1. Crie um DataFrame Pandas chamado `dados` a partir de `registros`.
2. Exiba os primeiros registros.
3. Determine a quantidade de linhas e colunas.
4. Liste os nomes dos atributos.
5. Utilize `info()`.
6. Utilize `describe()`.
7. Em Markdown, identifique quais atributos representam data/hora, área de carga e valor de carga.

**Antes de prosseguir, compreenda a estrutura efetivamente retornada pela API.**

In [6]:
# Desenvolva aqui o DESAFIO 1

In [7]:
dados = pd.DataFrame(registros)  # reconstrói do zero, sem renomes acumulados

In [8]:
dados.head()

,cod_areacarga,din_atualizacao,dat_referencia,din_referenciautc,val_cargaglobal,val_cargaglobalcons,val_cargaglobalsmmgd,val_cargasupervisionada,val_carganaosupervisionada,val_cargammgd,val_consistencia
0,SP,2026-08-14T05:58:29.574Z,2025-08-01,2025-08-01T03:30:00.000Z,15913.618,15913.618,15892.488,14421.112,1471.3759,21.13,0
1,SP,2026-08-14T05:58:29.574Z,2025-08-01,2025-08-01T04:00:00.000Z,15251.414,15251.414,15230.284,13758.101,1472.1840,21.13,0
2,SP,2026-08-14T05:58:29.574Z,2025-08-01,2025-08-01T04:30:00.000Z,14606.733,14606.733,14585.604,13112.602,1473.0022,21.13,0
3,SP,2026-08-14T05:58:29.574Z,2025-08-01,2025-08-01T05:00:00.000Z,14182.290,14182.290,14161.160,12687.433,1473.7275,21.13,0
4,SP,2026-08-14T05:58:29.574Z,2025-08-01,2025-08-01T05:30:00.000Z,13838.488,13838.488,13817.358,12342.648,1474.7096,21.13,0

In [9]:
dados.shape

(336, 11)

In [10]:
dados.columns

Index(['cod_areacarga', 'din_atualizacao', 'dat_referencia',
       'din_referenciautc', 'val_cargaglobal', 'val_cargaglobalcons',
       'val_cargaglobalsmmgd', 'val_cargasupervisionada',
       'val_carganaosupervisionada', 'val_cargammgd', 'val_consistencia'],
      dtype='object')

In [11]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cod_areacarga               336 non-null    object
 1   din_atualizacao             336 non-null    object
 2   dat_referencia              336 non-null    object
 3   din_referenciautc           336 non-null    object
 4   val_cargaglobal             336 non-null    float64
 5   val_cargaglobalcons         336 non-null    float64
 6   val_cargaglobalsmmgd        336 non-null    float64
 7   val_cargasupervisionada     336 non-null    float64
 8   val_carganaosupervisionada  336 non-null    float64
 9   val_cargammgd               336 non-null    float64
 10  val_consistencia            336 non-null    int64
dtypes: float64(6), int64(1), object(4)
memory usage: 29.0+ KB

In [12]:
dados.describe()

,val_cargaglobal,val_cargaglobalcons,val_cargaglobalsmmgd,val_cargasupervisionada,val_carganaosupervisionada,val_cargammgd,val_consistencia
count,336.000000,336.000000,336.000000,336.000000,336.000000,336.000000,336.0
mean,17870.828981,17870.828981,16953.421626,15495.799695,1457.621862,917.407249,0.0
std,3029.042438,3029.042438,2962.721503,2982.650359,34.888571,1253.581141,0.0
min,12139.253000,12139.253000,11549.664000,10054.455000,1391.990800,21.130000,0.0
25%,15110.533375,15110.533375,14457.604250,12990.878500,1433.112575,21.130000,0.0
50%,18199.128500,18199.128500,17045.260000,15611.629500,1453.981650,21.196900,0.0
75%,20386.629500,20386.629500,18931.679500,17502.643500,1479.430775,1793.579475,0.0
max,23185.312000,23185.312000,23164.182000,21717.934000,1538.274700,3736.009800,0.0

Data: dat_referencia, Hora:din_atualizacao, Área de carga: cod_carga,Valor de carga: val_cargaglobal

## DESAFIO 2 — Organização dos dados

1. Renomeie os principais atributos com nomes mais simples.
2. Crie um novo DataFrame contendo apenas os atributos necessários.
3. Verifique valores ausentes.
4. Caso existam, informe quantos há em cada atributo relevante.
5. Verifique se a variável de carga está em formato numérico.
6. Verifique como a data/hora está representada.
7. Registre em Markdown qualquer decisão de tratamento.

In [24]:
# Desenvolva aqui o DESAFIO 2

In [25]:
dados = dados.rename(columns={
    'dat_referencia': 'Data',
    'din_referenciautc': 'Hora',   # decidam: essa é a que varia de fato a cada 30 min
    'cod_areacarga': 'Area_Carga',
    'val_cargaglobal': 'Valor_Carga'
})

In [26]:

dados['Data'] = pd.to_datetime(dados['Data'])
dados['Hora'] = pd.to_datetime(dados['Hora'])

In [27]:
print(dados['Data'].dtype)
print(dados['Hora'].dtype)

datetime64[ns]
datetime64[ns, UTC]

In [28]:
necessario = dados[['Data', 'Hora', 'Area_Carga', 'Valor_Carga']].copy()

### Decisões de tratamento — Desafio 2

- Colunas renomeadas para nomes mais simples: `Data`, `Hora`, `Area_Carga`, `Valor_Carga`.
- Hora vem de `din_referenciautc` (varia a cada 30 min), não de `din_atualizacao` (só timestamp de atualização do registro).
- Sem valores ausentes.
- `Valor_Carga` já era numérico (float64).
- `Data` e `Hora` convertidas de texto para `datetime` com `pd.to_datetime()`.
- `necessario` mantém só as colunas relevantes pra análise.

In [29]:
dados.isnull().sum()

Area_Carga                    0
din_atualizacao               0
Data                          0
Hora                          0
Valor_Carga                   0
val_cargaglobalcons           0
val_cargaglobalsmmgd          0
val_cargasupervisionada       0
val_carganaosupervisionada    0
val_cargammgd                 0
val_consistencia              0
dtype: int64

In [30]:
dados['Valor_Carga'].dtype

dtype('float64')

In [31]:
dados['Data'].dtype
dados['Hora'].dtype

datetime64[ns, UTC]

## DESAFIO 3 — Indicadores da carga elétrica

Calcule:

1. carga mínima;
2. carga máxima;
3. carga média;
4. mediana;
5. amplitude entre máximo e mínimo;
6. quantidade total de medições.

Depois responda:

**O valor máximo está muito distante do comportamento médio observado? Justifique com os indicadores calculados.**

In [19]:
carga_minima = dados['Valor_Carga'].min()
carga_maxima = dados['Valor_Carga'].max()
print(f"a carga mínima é:", carga_minima, "a carga máxima é:",  carga_maxima)

a carga mínima é: 12139.253 a carga máxima é: 23185.312

In [20]:
carga_media = dados['Valor_Carga'].mean()
print(f"a carga média é:", carga_media)

a carga média é: 17870.828980654762

In [21]:
mediana= dados['Valor_Carga'].median()
print(f"a mediana é:", mediana)

a mediana é: 18199.1285

In [22]:
amplitude = carga_maxima - carga_minima
print(f"a amplitude é:", amplitude)

a amplitude é: 11046.059000000001

In [23]:
medições = dados['Valor_Carga'].count()
print(f"a quantidade de medições é:", medições)

a quantidade de medições é: 336

O valor máximo (23185,312) não está muito distante do comportamento médio da série. A diferença entre o máximo e a média (≈5314,48) é semelhante à diferença entre a média e o mínimo (≈5731,58), o que indica uma variação equilibrada em torno da média, e não uma concentração de valores baixos com um pico isolado no topo. Além disso, a proximidade entre média (17870,83) e mediana (18199,13) reforça que a distribuição é aproximadamente simétrica, sem indícios de outliers puxando os indicadores para cima. Portanto, o valor máximo representa um comportamento dentro da variação normal da carga elétrica medida, não um ponto discrepante

## DESAFIO 4 — Períodos de alta demanda

Considere como **alta demanda** os registros com carga superior a **90% da carga máxima**.

1. Calcule o limiar.
2. Crie um novo DataFrame com os registros acima dele.
3. Conte os registros.
4. Calcule o percentual em relação ao total.
5. Identifique o maior valor de carga.
6. Identifique a data e o horário do pico, quando disponíveis.

Responda:

**Os períodos próximos ao pico representam uma parcela grande ou pequena do período analisado?**

In [32]:
# Desenvolva aqui o DESAFIO 4

In [33]:
limiar_alta_demanda = carga_maxima * 0.90

print("Limiar de alta demanda:", limiar_alta_demanda)

Limiar de alta demanda: 20866.7808

In [34]:
alta_demanda = necessario[
    necessario["Valor_Carga"] > limiar_alta_demanda
].copy()

print("\nDataFrame de alta demanda:")
display(alta_demanda)

DataFrame de alta demanda:

          Data                      Hora Area_Carga  Valor_Carga
35  2025-08-01 2025-08-01 21:00:00+00:00         SP    21088.959
36  2025-08-01 2025-08-01 21:30:00+00:00         SP    22398.360
37  2025-08-01 2025-08-01 22:00:00+00:00         SP    23185.312
38  2025-08-01 2025-08-01 22:30:00+00:00         SP    22903.314
39  2025-08-01 2025-08-01 23:00:00+00:00         SP    22358.701
40  2025-08-01 2025-08-01 23:30:00+00:00         SP    21697.979
41  2025-08-01 2025-08-02 00:00:00+00:00         SP    21385.326
42  2025-08-01 2025-08-02 00:30:00+00:00         SP    20919.314
84  2025-08-02 2025-08-02 21:30:00+00:00         SP    20983.484
85  2025-08-02 2025-08-02 22:00:00+00:00         SP    21202.566
167 2025-08-04 2025-08-04 15:00:00+00:00         SP    20903.652
171 2025-08-04 2025-08-04 17:00:00+00:00         SP    20983.945
172 2025-08-04 2025-08-04 17:30:00+00:00         SP    21058.111
173 2025-08-04 2025-08-04 18:00:00+00:00         SP    20957.283
179 2025-08-04 2025-08-04 21:00:00+00:00         SP    21151.498
180 2025-08-04 2025-08-04 21:30:00+00:00         SP    22124.520
181 2025-08-04 2025-08-04 22:00:00+00:00         SP    22691.178
182 2025-08-04 2025-08-04 22:30:00+00:00         SP    22602.280
183 2025-08-04 2025-08-04 23:00:00+00:00         SP    22387.479
184 2025-08-04 2025-08-04 23:30:00+00:00         SP    21873.928
185 2025-08-04 2025-08-05 00:00:00+00:00         SP    21625.650
186 2025-08-04 2025-08-05 00:30:00+00:00         SP    21180.598
214 2025-08-05 2025-08-05 14:30:00+00:00         SP    20950.814
215 2025-08-05 2025-08-05 15:00:00+00:00         SP    20988.578
227 2025-08-05 2025-08-05 21:00:00+00:00         SP    21427.500
228 2025-08-05 2025-08-05 21:30:00+00:00         SP    22441.875
229 2025-08-05 2025-08-05 22:00:00+00:00         SP    23142.227
230 2025-08-05 2025-08-05 22:30:00+00:00         SP    23019.832
231 2025-08-05 2025-08-05 23:00:00+00:00         SP    22625.648
232 2025-08-05 2025-08-05 23:30:00+00:00         SP    22089.646
233 2025-08-05 2025-08-06 00:00:00+00:00         SP    21937.125
234 2025-08-05 2025-08-06 00:30:00+00:00         SP    21502.771
275 2025-08-06 2025-08-06 21:00:00+00:00         SP    21192.049
276 2025-08-06 2025-08-06 21:30:00+00:00         SP    22320.617
277 2025-08-06 2025-08-06 22:00:00+00:00         SP    23149.518
278 2025-08-06 2025-08-06 22:30:00+00:00         SP    22975.998
279 2025-08-06 2025-08-06 23:00:00+00:00         SP    22521.299
280 2025-08-06 2025-08-06 23:30:00+00:00         SP    22248.188
281 2025-08-06 2025-08-07 00:00:00+00:00         SP    21846.860
282 2025-08-06 2025-08-07 00:30:00+00:00         SP    21264.129
321 2025-08-07 2025-08-07 20:00:00+00:00         SP    20882.361
323 2025-08-07 2025-08-07 21:00:00+00:00         SP    21292.605
324 2025-08-07 2025-08-07 21:30:00+00:00         SP    22420.307
325 2025-08-07 2025-08-07 22:00:00+00:00         SP    23131.060
326 2025-08-07 2025-08-07 22:30:00+00:00         SP    23026.836
327 2025-08-07 2025-08-07 23:00:00+00:00         SP    22632.068
328 2025-08-07 2025-08-07 23:30:00+00:00         SP    22225.947
329 2025-08-07 2025-08-08 00:00:00+00:00         SP    22076.066
330 2025-08-07 2025-08-08 00:30:00+00:00         SP    21716.170
331 2025-08-07 2025-08-08 01:00:00+00:00         SP    20930.443

In [35]:
quantidade_alta_demanda = alta_demanda["Valor_Carga"].count()

print("\nQuantidade de registros de alta demanda:",
      quantidade_alta_demanda)

Quantidade de registros de alta demanda: 50

In [36]:
percentual_alta_demanda = (
    quantidade_alta_demanda / medições
) * 100

print("Percentual de alta demanda:",
      f"{percentual_alta_demanda:.2f}%")

Percentual de alta demanda: 14.88%

In [37]:
maior_carga = alta_demanda["Valor_Carga"].max()

print("Maior valor de carga:", maior_carga)

Maior valor de carga: 23185.312

In [38]:
indice_pico = alta_demanda["Valor_Carga"].idxmax()

data_pico = alta_demanda.loc[indice_pico, "Data"]
hora_pico = alta_demanda.loc[indice_pico, "Hora"]

print("Data do pico:", data_pico)
print("Horário do pico:", hora_pico)

Data do pico: 2025-08-01 00:00:00
Horário do pico: 2025-08-01 22:00:00+00:00

In [39]:
# Conclusão
print("\nConclusão:")
print(
    f"Os períodos próximos ao pico representam uma parcela "
    f"{'grande' if percentual_alta_demanda >= 25 else 'pequena'} "
    f"do período analisado, correspondendo a "
    f"{percentual_alta_demanda:.2f}% das {medições} medições."
)

Conclusão:
Os períodos próximos ao pico representam uma parcela pequena do período analisado, correspondendo a 14.88% das 336 medições.

## DESAFIO 5 — Segundo critério de análise

Crie um segundo recorte dos dados utilizando um critério definido pela equipe.

Possibilidades:

- carga acima da média;
- carga abaixo de uma porcentagem do máximo;
- intervalo de valores;
- determinado dia ou período;
- combinação de duas condições.

Apresente:

1. o critério escolhido;
2. o novo DataFrame;
3. a quantidade de registros;
4. o percentual;
5. a comparação com o conjunto de alta demanda.

In [44]:
# Desenvolva aqui o DESAFIO 5

# 1. Critério escolhido: Registros com Valor_Carga abaixo da média

print("Critério escolhido: carga abaixo da média")
print("Carga média:", carga_media)

abaixo_da_media = necessario[
    necessario["Valor_Carga"] < carga_media
].copy()

print("\nDataFrame com carga abaixo da média:")
display(abaixo_da_media)


# 2. Quantidade de registros, percentual e comparações
quantidade_abaixo_media = abaixo_da_media["Valor_Carga"].count()

print("\nQuantidade de registros abaixo da média:",
      quantidade_abaixo_media)

percentual_abaixo_media = (
    quantidade_abaixo_media / medições
) * 100

print("Percentual abaixo da média:",
      f"{percentual_abaixo_media:.2f}%")

print("\n--- Comparação ---")

print(
    f"Alta demanda: {quantidade_alta_demanda} registros "
    f"({percentual_alta_demanda:.2f}%)"
)

print(
    f"Abaixo da média: {quantidade_abaixo_media} registros "
    f"({percentual_abaixo_media:.2f}%)"
)

print("\nConclusão:")

if quantidade_abaixo_media > quantidade_alta_demanda:
    print(
        "O conjunto de registros abaixo da média é maior "
        "do que o conjunto de alta demanda."
    )
else:
    print(
        "O conjunto de registros de alta demanda é maior "
        "do que o conjunto abaixo da média."
    )

Critério escolhido: carga abaixo da média
Carga média: 17870.828980654762

DataFrame com carga abaixo da média:

          Data                      Hora Area_Carga  Valor_Carga
0   2025-08-01 2025-08-01 03:30:00+00:00         SP    15913.618
1   2025-08-01 2025-08-01 04:00:00+00:00         SP    15251.414
2   2025-08-01 2025-08-01 04:30:00+00:00         SP    14606.733
3   2025-08-01 2025-08-01 05:00:00+00:00         SP    14182.290
4   2025-08-01 2025-08-01 05:30:00+00:00         SP    13838.488
..         ...                       ...        ...          ...
298 2025-08-07 2025-08-07 08:30:00+00:00         SP    14908.752
299 2025-08-07 2025-08-07 09:00:00+00:00         SP    15844.801
300 2025-08-07 2025-08-07 09:30:00+00:00         SP    17206.496
301 2025-08-07 2025-08-07 10:00:00+00:00         SP    17379.400
335 2025-08-07 2025-08-08 03:00:00+00:00         SP    17271.514

[152 rows x 4 columns]

Quantidade de registros abaixo da média: 152
Percentual abaixo da média: 45.24%

--- Comparação ---
Alta demanda: 50 registros (14.88%)
Abaixo da média: 152 registros (45.24%)

Conclusão:
O conjunto de registros abaixo da média é maior do que o conjunto de alta demanda.

## DESAFIO 6 — Visualização

Construa **pelo menos dois gráficos**.

- Um deve representar o comportamento da carga ao longo das observações ou do tempo.
- O segundo deve ser escolhido pela equipe.

Inclua título, eixos e unidades quando aplicável.

Após cada gráfico, escreva uma interpretação curta.

In [ ]:
# Desenvolva aqui o DESAFIO 6

## DESAFIO 7 — Síntese para o relatório

Crie uma variável `resumo_resultados` contendo pelo menos:

- região;
- período;
- quantidade de registros;
- carga mínima;
- carga máxima;
- carga média;
- mediana;
- limiar de alta demanda;
- quantidade e percentual de alta demanda;
- momento do pico;
- resultado do segundo critério.

A IA deverá receber **resultados produzidos por vocês**, e não substituir a análise.

In [ ]:
# Exemplo de estrutura:
#
# resumo_resultados = f'''
# Região analisada: ...
# Período analisado: ...
# Quantidade de registros: ...
# Carga mínima: ...
# Carga máxima: ...
# Carga média: ...
# Mediana: ...
# Limiar de alta demanda: ...
# Registros de alta demanda: ...
# Percentual de alta demanda: ...
# Momento do pico: ...
# Segundo critério: ...
# '''
#
# print(resumo_resultados)

# OPCIONAL: Relatório técnico com apoio do Gemini

No Colab:

1. abra **Secrets**;
2. crie `GEMINI_API_KEY`;
3. informe sua chave;
4. permita o acesso do notebook ao secret.

**Não coloque a chave diretamente no código.**

In [ ]:
!pip -q install -U google-genai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 48.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.7/259.7 kB 17.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.57.0 which is incompatible.

In [ ]:
from google.colab import userdata
from google import genai

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=GEMINI_API_KEY)

SecretNotFoundError: Secret GEMINI_API_KEY does not exist.

## DESAFIO 8 — Geração do relatório

O relatório deve:

- usar os resultados calculados;
- apresentar os principais indicadores;
- destacar o pico e os períodos de alta demanda;
- comparar os dois critérios;
- não inventar causas;
- diferenciar observações de hipóteses;
- terminar com uma conclusão.

In [ ]:
prompt = f'''
Atue como analista de dados do setor elétrico.

Produza um relatório técnico curto com base EXCLUSIVAMENTE nos resultados abaixo.

Não invente causas para as variações observadas.
Não apresente como fato explicações que não possam ser sustentadas pelos dados.
Diferencie claramente resultados observados de hipóteses.

Inclua:
1. caracterização do conjunto analisado;
2. principais indicadores;
3. análise dos períodos de alta demanda;
4. comparação com o segundo critério;
5. conclusão.

RESULTADOS DA EQUIPE:

{resumo_resultados}
'''

In [ ]:
response_gemini = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt
)

print(response_gemini.text)

## DESAFIO 9 — Validação crítica

Compare o texto gerado pelo Gemini com os cálculos, DataFrames e gráficos.

Responda:

1. Os indicadores foram utilizados corretamente?
2. Há alguma afirmação que não pode ser confirmada pelos dados?
3. Houve interpretação exagerada ou causalidade não demonstrada?
4. Que alterações a equipe realizou no texto?

## Relatório final

Insira abaixo a versão final revisada pela equipe.

_Escreva aqui a versão final revisada._

---

## Entrega

O notebook deve apresentar:

- consulta à API executada;
- DataFrame criado;
- inspeção e organização dos dados;
- indicadores;
- pelo menos dois DataFrames derivados por critérios;
- percentuais;
- pelo menos dois gráficos;
- interpretações;
- síntese para a IA;
- relatório com apoio do Gemini;
- validação crítica;
- versão final revisada.

**Entregue somente este Notebook (.ipynb), com todas as células executadas e os resultados visíveis.**